name:                javac
version:             0.1.0.0
github:              "rowland66/haskell-javac"
license:             BSD3
author:              "Rowland Smith"
maintainer:          "rowls66@gmail.com"
copyright:           "2022 Rowland Smith"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rowland-shapes#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- transformers
- Glob
- binary
- bytestring
- text
- directory
- vector
- split
- filepattern
- text-show
- extra
- tuple
- monadlist
- monad-loops
- enumset
- validation

library:
  source-dirs: src
  exposed-modules: 
  - Compiler

executables:
  hjavac:
    main:                Main.hs
    source-dirs:         driver
    dependencies:
    - javac

tests:
  typechecker:
    main:               TypeCheckerTests.hs
    source-dirs:        
    - src
    - tests
    dependencies:
    - HUnit
    - test-framework
    - test-framework-hunit
